steps:
- name: 'gcr.io/k8s-skaffold/pack'
  entrypoint: 'pack'
  args:
    - 'build'
    - '$_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$SERVICE_NAME:$COMMIT_SHA'
    - '--builder=gcr.io/buildpacks/builder:v1'
    - '--env=NEXT_PUBLIC_SUPABASE_URL=$_SUPABASE_URL' # Mengambil dari variable GCP
    - '--env=NEXT_PUBLIC_SUPABASE_ANON_KEY=$_SUPABASE_ANON_KEY'